### ISSUE TITLE
domain_suffix changes in 2.043000

### ISSUE THREAD

**Issue by inphobia** [netdisco/nd2-web-plugin-rancid#3]
2.043000 changed domain_suffix from a single item to a list. since this extension uses that config setting:

https://github.com/netdisco/nd2-web-plugin-rancid/blob/59a8dda2dfdfe2b2f352e11524c0a66b5e634da5/lib/App/NetdiscoX/Web/Plugin/RANCID.pm#L31

https://github.com/netdisco/nd2-web-plugin-rancid/blob/59a8dda2dfdfe2b2f352e11524c0a66b5e634da5/lib/App/NetdiscoX/Web/Plugin/RANCID.pm#L55

we'll most likely need some more logic or changes to make this behave as expected.

see:
* https://github.com/netdisco/netdisco/issues/591
* https://github.com/netdisco/netdisco/issues/644

**Comment by ollyg** [comment]
I don't think this is a problem because the "list" of domain_suffix is actually quietly converted to a single regular expression inside Netdisco, so can then be used just fine.

Closing this, but if you did have the code explode with a list, do let me know!
