### ISSUE TITLE
 "check_acl" is not exported by the App::Netdisco::Util::Permission module

### ISSUE THREAD

**Issue by caralo** [netdisco/nd2-web-plugin-rancid#4]
There must be something wrong in App:Netdisco (at least with version 2.062002) in the way it checks acls if rancid plugin is active.
I get the following error when I try to start netdisco-web:

**Error while loading /var/lib/netdisco/perl5/bin/netdisco-web-fg: "check_acl" is not exported by the App::Netdisco::Util::Permission module**
Can't continue after import errors at /var/lib/netdisco/perl5/lib/perl5/App/NetdiscoX/Web/Plugin/RANCID.pm line 12.
BEGIN failed--compilation aborted at /var/lib/netdisco/perl5/lib/perl5/App/NetdiscoX/Web/Plugin/RANCID.pm line 12.
Compilation failed in require at /usr/share/perl/5.28/Module/Load.pm line 77.
Can't locate App/NetdiscoX/Web/Plugin/RANCID in @INC (@INC contains: /var/lib/netdisco/site_plugins /var/lib/netdisco/perl5/lib/perl5/auto/share/dist/App-Netdisco/lib /var/lib/netdisco/perl5/lib /var/lib/netdisco/perl5/bin/lib /var/lib/netdisco/perl5/lib/perl5/5.28.1/x86_64-linux-gnu-thread-multi /var/lib/netdisco/perl5/lib/perl5/5.28.1 /var/lib/netdisco/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /var/lib/netdisco/perl5/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /var/lib/netdisco/perl5/lib/perl5/5.28.0 /var/lib/netdisco/perl5/lib/perl5/5.28.0/x86_64-linux-gnu-thread-multi /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl/5.28/Module/Load.pm line 77.
Compilation failed in require at /var/lib/netdisco/perl5/bin/netdisco-web-fg line 59.
BEGIN failed--compilation aborted at /var/lib/netdisco/perl5/bin/netdisco-web-fg line 59.

If I disable rancid plugin, everything works ok.

**Comment by ollyg** [comment]
Hi, this is an error in Netdisco which we will patch for, but in the meantime another user has kindly patched this module.

Fixed in 5bd1fddf9c7f53b6e7c6eeab681236082f691e86 and will be in the next release.
